### PR TITLE
Camcoder

### PR DESCRIPTION
**Pull request by Pablo-source**
This is an example on how to create animated GIF using Camcoder package

### CODE REVIEW

**Comment by Pablo-source** [comment]
Keep it open because I want it to be merged with the main demos-and-how-to

**Comment by ChrisBeeley** [comment]
This is great, thank you! I'm wondering if we should .gitignore the .png files to clean up the PR a bit, any thoughts @Lextuga007 @tomjemmett ?

**Comment by tomjemmett** [comment]
I would typically argue that items that are generated by code, e.g. these `.png`'s should be `.gitignore`'d as they can always be generated again, and as such should be rendered in an action when `gh-pages` are deployed... that said, we currently aren't utilising actions to deploy the content.

one thing to note is git repo's can get bloated very quickly with lot's of binary files, at a very quick glance there appears to be ~10 `.png`'s at ~150Kb, and one `.gif` at ~1Mb.

so I think we should exclude these, then do a squash merge (that should drop these file from the commit history)

**Comment by ChrisBeeley** [comment]
Is that OK @Pablo-source ? We can do the changes for you or you can resubmit if you prefer. Not to be pedantic but it's good to keep the repo clean 🧹

**Comment by Pablo-source** [comment]
Hi @ChrisBeeley  and @tomjemmett  many thanks for your suggestions, I am going to include  in the .gitignore all the .png files as both suggested.  I will do one commit today with this change to exclude those files produced by camcoder. I will keep only the R script and the GIF output file produced if that is fine.

**Comment by Pablo-source** [comment]
Many thanks @ChrisBeeley  and @tomjemmett . Learning a log on this first pull to this repo. Ammending right now the .gitignore file to exclude all .png filles and I will commit it again in the next 40 minutes.

**Comment by ChrisBeeley** [comment]
> Many thanks @ChrisBeeley and @tomjemmett . Learning a log on this first pull to this repo. Ammending right now the .gitignore file to exclude all .png filles and I will commit it again in the next 40 minutes.

Great to hear- that's what NHS-R is all about- learning by doing. Thanks for the PR 🤗

**Comment by ChrisBeeley** [comment]
I've tidied this up into a new PR #55 . Sorry I should have done it properly really. 

@Pablo-source , please take a look and see what you think. I've requested a review from @Lextuga007

**Comment by ChrisBeeley** [comment]
Is this PR finished and ready for review?

**Comment by Lextuga007** [comment]
Yes, but @Pablo-source has made some changes to his own branch and this needs to be merged into that. I tried merging your branch to Pablo's locally but got merge conflicts on the data files.

**Comment by Lextuga007** [comment]
Resolved with #55

**Pull request closed without merging**
